version: '2'
services:
  postgres:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pset123456
      POSTGRES_DB: collaboration
      PGDATA: /var/lib/postgresql/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/pgdata
#volumes:
#  pgdata: