apiVersion: v1
kind: Service
metadata:
  name: {{ include "koala.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "koala.name" . }}-web
    helm.sh/chart: {{ include "koala.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-web
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{if (and (not (empty .Values.web.service.nodePort)) (eq .Values.web.service.type "NodePort") )}}
      nodePort: {{.Values.web.service.nodePort}}
      {{end}}
  selector:
    app.kubernetes.io/name: {{ include "koala.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}-web
